### ISSUE TITLE
Rlifesrc is missing still lives

### ISSUE THREAD

**Issue by yujh-yujh** [AlephAlpha/rlifesrc#162] opened 2022-02-05 19:30 UTC
I have recently did a 3x3 sl search and I had this result:

`Find all results. Won't stop when found one.

x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
oo.$
o.o$
.oo!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
oo.$
o.o$
.o.!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
o..$
ooo$
..o!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
oo.$
.o.$
.oo!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
.oo$
o.o$
oo.!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
.o.$
o.o$
oo.!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
..o$
ooo$
o..!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
.oo$
o.o$
.o.!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
.o.$
o.o$
.oo!
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
.o.$
o.o$
.o.!
`

and I've found another rotation of one of the still lives and it's not listed. It's b2o$bo$2o! I think this one is very easy to reproduce, It's just B3/S23-a4z

**Comment by AlephAlpha** [comment] 2022-02-06 11:02
Because there is already this:

```
x = 3, y = 3, rule = B34kz5e7c8/S23-a4ityz5k
oo.$
.o.$
.oo!
```

which is symmetric to `b2o$bo$2o!`. Rlifesrc would skip some symmetric results to reduce the search time. This is a feature, not a bug.

If you can read Chinese, please see #81 . `b2o$bo$2o!` is skipped because of the "半个前排" rule.

**Comment by AlephAlpha** [comment] 2022-02-15 01:29
I'll close this. If there are other issues you can reopen it.

**Closed by AlephAlpha** 2022-02-15 01:29 UTC
Labels: bug, wontfix
